### ISSUE TITLE
undefined method `datauri' for Metanorma::Utils:Module (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-utils#9]
[ -d build/iso ] || git clone --recurse-submodules https://metanorma-ci:788a9031a72af5e0ee065167c03597c2d7cd9c7c@github.com/metanorma/mn-samples-iso build/iso; \
	build/metanorma site generate build/iso -c build/iso/metanorma.yml -o site/iso --agree-to-terms
Cloning into 'build/iso'...
[info]: Compiling /Users/runner/work/packed-mn/packed-mn/build/iso/sources/amendment/rice-amd.awi.adoc ...
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/cleanup.rb:175:in `block in img_cleanup': undefined method `datauri' for Metanorma::Utils:Module (NoMethodError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/cleanup.rb:175:in `img_cleanup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/cleanup.rb:67:in `cleanup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:168:in `makexml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:142:in `document'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/input/asciidoc.rb:24:in `process'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/compile.rb:122:in `process_input'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/compile.rb:21:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:81:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:23:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli.rb:67:in `start'
	from /__enclose_io_memfs__/local/metanorma:198:in `<main>'
make[1]: *** [test-flavor] Error 1

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse can we safely release this gem right now?

**Comment by CAMOBAP** [comment]
oh actually it's released, but for some reason, it resolved to 1.0.4

I will investigate

**Comment by CAMOBAP** [comment]
Closed in favor https://github.com/metanorma/packed-mn/issues/86
